/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Main: typeof import('./src/components/Main/Main.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputAdornment: typeof import('tdesign-vue-next')['InputAdornment']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
